services:
    _defaults:
        autowire: true
        autoconfigure: true

    numero2\PCALoginBundle\Controller\FrontendModule\LoginPCAController:
        arguments:
            - '@contao.security.frontend_user_provider'
            - '@contao.security.user_checker'
            - '@contao.csrf.token_manager'
            - '@security.authentication_utils'
            - '@security.authorization_checker'
            - '@security.logout_url_generator'
            - '@security.token_storage'
            - '@contao.translation.translator'
            - '@http_client'
            - '@event_dispatcher'
            - '@monolog.logger.contao.access'
